{% set name = "libint" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evaleev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: e001ad5bf5bcb51a6355da25348cd449a7173c81e61fb58cd1ccfd5e492befa6

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - boost-cpp
    - eigen
    - gmp
    - mpfr
      
test:
  commands:
    # Verify library
    - test -f "${PREFIX}/lib/libint2${SHLIB_EXT}"
    # Inspect linkage
    - ldd -r -u "${PREFIX}/lib/libint2${SHLIB_EXT}" && return 0
    - ldd -v "${PREFIX}/lib/libint2${SHLIB_EXT}"

about:
    home: https://github.com/evaleev/libint
    dev_url: https://github.com/evaleev/libint    
    doc_url: https://github.com/evaleev/libint/wiki
    license: LGPL-3.0+
    license_url: https://opensource.org/licenses/LGPL-3.0+
    license_file: LICENSE
    license_family: LGPL
    summary: "Libint is a high-performance library for computing Gaussian integrals in quantum mechanics"

extra:
  recipe-maintainers:
    - felipeZ
