{% set name = "libint" %}
{% set version = "2.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evaleev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: a7306f1998a4c0a0babc13d480c62de2631674918e3562c78fb602c77efe0b94

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - boost-cpp
    - eigen
    - openmp

test:
  commands:
    # Verify library
    - test -f "${PREFIX}/lib/libint2${SHLIB_EXT}"
    # Inspect linkage
    - ldd -r -u "${PREFIX}/lib/libint2${SHLIB_EXT}" && return 0  # [linux]
    - ldd -v "${PREFIX}/lib/libint2${SHLIB_EXT}"                 # [linux]

about:
  home: https://github.com/evaleev/libint
  dev_url: https://github.com/evaleev/libint
  doc_url: https://github.com/evaleev/libint/wiki
  license: LGPL-3.0+
  license_url: https://opensource.org/licenses/LGPL-3.0+
  license_file: LICENSE
  license_family: LGPL
  summary: Libint is a high-performance library for computing Gaussian integrals in quantum mechanics

extra:
  recipe-maintainers:
    - felipeZ
