{% set name = "libint" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evaleev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: 30e6ff493c44e2bf6fdf43cd6a4fdcdc552ee81f9a200e270b402b5dda87fb35

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - boost-cpp
    - cmake
    - eigen
    - openmp

test:
  commands:
    # Verify library
    - test -f "${PREFIX}/lib/libint2${SHLIB_EXT}"
    # Inspect linkage
    - ldd -r -u "${PREFIX}/lib/libint2${SHLIB_EXT}" && return 0  # [linux]
    - ldd -v "${PREFIX}/lib/libint2${SHLIB_EXT}"                 # [linux]

about:
  home: https://github.com/evaleev/libint
  dev_url: https://github.com/evaleev/libint
  doc_url: https://github.com/evaleev/libint/wiki
  license: LGPL-3.0+
  license_url: https://opensource.org/licenses/LGPL-3.0+
  license_file: LICENSE
  license_family: LGPL
  summary: Libint is a high-performance library for computing Gaussian integrals in quantum mechanics

extra:
  recipe-maintainers:
    - felipeZ
